config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Routes for Profiles
  get 'profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  patch 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id/merchant', to: 'profiles#merchant', as: 'profile_merchant'
  patch 'profiles/:id/customer', to: 'profiles#customer', as: 'profile_customer'

  # Routes for Addresses
  get 'addresses/new', to: 'addresses#new', as: 'new_address'
  post 'addresses', to: 'addresses#create'
  get 'addresses/:id/edit', to: 'addresses#edit', as: 'edit_address'
  patch '/addresses/:id', to: 'addresses#update', as: 'address'
  delete 'addresses/:id', to: 'addresses#destroy'
  

  # Routes for Inventories. These *only* need to be created.
  get 'inventories/:id', to: 'inventories#show', as: 'inventory'

  # Routes for Coffees
  get 'coffees', to: 'coffees#index'
  get 'coffees/new', to: 'coffees#new', as: 'new_coffee'
  post 'coffees', to: 'coffees#create'
  get 'coffees/:id/edit', to: 'coffees#edit', as: 'edit_coffee'
  post 'coffees/:id/edit', to: 'coffees#update'
  get 'coffees/:id/', to: 'coffees#show', as: 'coffee'
  delete 'coffees/:id', to: 'coffees#destroy'
  patch '/coffees/:id', to: 'coffees#update'

  # Routes for Carts
  get 'carts', to: 'carts#index', as: 'carts'
  get 'coffees/:id/carts/new', to: 'carts#create', as: 'new_cart'
  patch 'carts/:id/+1', to: 'carts#increase', as: 'cart_increase'
  patch 'carts/:id/-1', to: 'carts#decrease', as: 'cart_decrease'
  delete 'carts/checkout', to: 'carts#checkout', as: 'checkout'
  delete 'carts/:id', to: 'carts#remove', as: 'cart'

  root to: 'coffees#index'
end

app/models/coffee.rb
class Coffee < ApplicationRecord
  belongs_to :inventory
  has_many :carts, dependent: :destroy
  has_many :profiles, through: :cart

  has_one_attached :coffee_image

  validates :name, presence: true
  validates :origin, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :roast_type, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :check_auth, except: %i[index]
  before_action :authenticate_user!, except: [:index]
  before_action :set_coffee, only: %i[show edit update destroy]
  before_action :set_inventory, only: %i[new create update destroy]

  def show
  end

  def new
    @coffee = @inventory.coffees.build
  end

  def create
    @coffee = @inventory.coffees.build(coffee_params)

    if @coffee.save
      redirect_to @inventory
      flash[:notice] = 'Coffee added'
    else
      flash[:alert] = @coffee.errors.full_messages.join('<br />').html_safe
      render 'new'
    end
  end

  def edit
  end

  def update
      @coffee.update!(coffee_params)
      redirect_to @inventory
    rescue StandardError => e
      flash[:alert] = e
      render 'edit'
  end

  def destroy
    @coffee.coffee_image.purge
    @coffee.destroy
    redirect_to @inventory
    flash[:notice] = 'Coffee Removed'
  end

  private

  def set_inventory
    @inventory = current_user.profile.inventory
  end

  def set_coffee
    @coffee = Coffee.find(params[:id])
  end

  def check_auth
    authorize Coffee
  end

  def coffee_params
    return params.require(:coffee).permit(:name, :origin, :description, :price, :roast_type, :coffee_image, :quantity)
  end
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/views/coffees/_form.html.erb
<%= form_with(model: @coffee, data: {turbo: false}) do |f| %>
 
  <div class='field'>
    <fieldset class='control'>
        <%= f.label :coffe_image %><br />
        <%= f.file_field :coffee_image %>
    </fieldset>
  </div>

  <div class='field is-horizontal'>
    <fieldset class='control'>
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'input' %>
    </fieldset>
  </div>

  <div class='field is-horizontal'>
    <fieldset class='control'>
      <%= f.label :origin %><br />
      <%= f.text_field :origin, class: 'input' %>
    </fieldset>
  </div>

  <div class='field is-horizontal'>
    <fieldset class='control'>
      <%= f.label :description %><br />
      <%= f.text_field :description, class: 'input' %>
    </fieldset>
  </div>

  <div class='field is-horizontal'>
    <fieldset class='control'>
      <%= f.label :price %><br />
      <%= f.number_field :price, class: 'input' %>
    </fieldset>
  </div>

  <div class='field is-horizontal'>
    <fieldset class='control'>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'input' %>
    </fieldset>
  </div>

  <br />

  <div class='field'>
    <div class='select'>
      <%= f.select(:roast_type, options_for_select([['Roast Style', nil], ['Espresso', 'Espresso'], ['Filter', 'Filter'], ['Omni', 'Omni']], 4)) %><br />
    </div>
  </div>

  <div class='actions'>
    <%= f.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<h1>Change Coffee Details</h1>

<%= render 'form' %>

app/views/coffees/index.html.erb
<h1>The Coffee Bazaar</h1>

<%# Parent container for Coffee tiles as per Bulma guidelines %>
<div class="tile is-ancestor is-flex-wrap-wrap is-justify-content-space-around">
  <% Coffee.all.each do |coffee| %>

    <%# Individual tiles for each coffee with seperate containers for each element name/price/image/etc for FlexBox alignment, as per Bulma guidelines %>
    <div class='tile is-5 is-vertical m-3'>
      <div class='is-child has-background-info-light has-text-centered is-flex-direction-column'>
        <figure class='image m-2 is-inline-block', style='max-width:20vw'>
          <%= cl_image_tag(coffee.coffee_image.key, crop: :scale, width: 150, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if coffee.coffee_image.attached? %>
        </figure>
        <p class='title is-flex is-justify-content-center'>
          <%= "#{coffee.origin}" + " #{coffee.name}"  %>
        </p>
        <p class='is-flex is-justify-content-center'>
          <%= coffee.roast_type %>
          </p>
        <p class='is-flex is-justify-content-center'>
          <%= coffee.price %>
        </p>      
        <div class='is-flex is-justify-content-center'>
          <%= link_to("Details", coffee_path(coffee), class: 'button is-success') %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/coffees/new.html.erb
<h1>Add New Coffee</h1>

<%= render 'form' %>

app/views/coffees/show.html.erb
<h1><%= "#{@coffee.origin} #{@coffee.name}" %></h1>

<%= cl_image_tag(@coffee.coffee_image.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if @coffee.coffee_image.attached? %>

<section class='block m-3'>
    <table class='table'>
      <tr>
        <td><%= 'Roast Type:' %></td>
        <td><%= @coffee.roast_type %></td>
      </tr>
      <tr>
        <td><%= 'Description:' %></td>
        <td><%= @coffee.description %></td>
      </tr>
      <tr>
        <td><%= 'Price:' %></td>
        <td><%= @coffee.price %></td>
      </tr>
      <tr>
        <td><%= 'Qty Availabile:' %></td>
        <td><%= @coffee.quantity %></td>
      </tr>
      <tr>
        <td><%= user_signed_in? && policy(Cart).new? && @coffee.quantity.positive? ? link_to("Add to Cart", new_cart_path, class: 'button is-success') : '' %></td>
      </tr>
      </table>
  </section>

  