config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Routes for Profiles
  get 'profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  patch 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id/merchant', to: 'profiles#merchant', as: 'profile_merchant'
  patch 'profiles/:id/customer', to: 'profiles#customer', as: 'profile_customer'

  # Routes for Addresses
  get 'addresses/new', to: 'addresses#new', as: 'new_address'
  post 'addresses', to: 'addresses#create'
  get 'addresses/:id/edit', to: 'addresses#edit', as: 'edit_address'
  patch '/addresses/:id', to: 'addresses#update', as: 'address'
  delete 'addresses/:id', to: 'addresses#destroy'
  

  # Routes for Inventories. These *only* need to be created.
  get 'inventories/:id', to: 'inventories#show', as: 'inventory'

  # Routes for Coffees
  get 'coffees', to: 'coffees#index'
  get 'coffees/new', to: 'coffees#new', as: 'new_coffee'
  post 'coffees', to: 'coffees#create'
  get 'coffees/:id/edit', to: 'coffees#edit', as: 'edit_coffee'
  post 'coffees/:id/edit', to: 'coffees#update'
  get 'coffees/:id/', to: 'coffees#show', as: 'coffee'
  delete 'coffees/:id', to: 'coffees#destroy'
  patch '/coffees/:id', to: 'coffees#update'

  # Routes for Carts
  get 'carts', to: 'carts#index', as: 'carts'
  get 'coffees/:id/carts/new', to: 'carts#create', as: 'new_cart'
  patch 'carts/:id/+1', to: 'carts#increase', as: 'cart_increase'
  patch 'carts/:id/-1', to: 'carts#decrease', as: 'cart_decrease'
  delete 'carts/checkout', to: 'carts#checkout', as: 'checkout'
  delete 'carts/:id', to: 'carts#remove', as: 'cart'

  root to: 'coffees#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  rolify
  belongs_to :user

  has_many :addresses, dependent: :destroy
  has_one :inventory, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :coffees, through: :cart

  has_one_attached :profile_picture

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :contact_number, presence: true, length: { in: 8..10  }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile
  before_action :check_auth

  after_action :verify_authorized

  def show
  end

  def new
    @profile.build
  end

  def create
    @profile.build.create(profile_params)

    if @profile.save
      redirect_to @profile
    else
      flash[:alert] = @profile.errors.full_messages
    end
  end

  # Adds merchant role to profile and creates inventory
  def merchant
    @profile.add_role :merchant
    @profile.create_inventory!
    redirect_to @profile
  end

  # Adds customer roles to profile
  def customer
    @profile.add_role :customer
    redirect_to @profile
  end

  def edit
  end

  def update
      @profile.update!(profile_params)
      flash[:notice] = 'Details Updated!'
      redirect_to @profile
    rescue StandardError => e
      flash[:alert] = e
      render 'edit'
  end

  def destroy
    @profile.profile_picture.purge
    @profile.destroy
  end

  private

  def check_auth
    authorize @profile
  end

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    return params.require(:profile).permit(:user_id, :roles, :username, :name, :contact_number, :profile_picture)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: @profile, data: {turbo: false}) do |f| %>
  
  <%# Profile attributes %>
  <ul>
  <% @profile.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  
  <fieldset class='field'>
    <%= f.label :profile_picture %>
    <%= f.file_field :profile_picture %>
  </fieldset>
  <fieldset class='field'>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </fieldset>
  <fieldset class='field'>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </fieldset>
  <fieldset class='field'>
    <%= f.label :contact_number %><br />
    <%= f.number_field :contact_number %>
  </fieldset>
  
  <p>
    <%= f.submit 'Update', class: 'button is-primary' %>
  </p>
<% end %>

app/views/profiles/edit.html.erb
<h1>Change Account Details</h1>

<%= render 'form' %>

app/views/profiles/new.html.erb
<h1>New Account Details</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<h1>Your Account</h1>



<%= link_to("Security / Login Details", edit_user_registration_path, class: 'button is-warning') %>
<br />
<br />

<%# Assigns role to user profile if none present, before dispaying profile contents %>
<% if (@profile.has_any_role? :merchant, :customer) == false %>
  <p>Please choose an acount type:</p>
  <%= button_to('Merchant', profile_merchant_path(@profile), method: :patch, form: { data: { turbo_confirm: 'Are you sure you want a Merchant account?' } }, class: 'button is-info') %><br />
  <%= button_to('Customer', profile_customer_path(@profile), method: :patch, form: { data: { turbo_confirm: 'Are you sure you want a Customer account?' } }, class: 'button is-info') %>
<% else %>
  <%= cl_image_tag(@profile.profile_picture.key, crop: :scale, width: 150, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if current_user.profile.profile_picture.attached? %>

  <section class='block'>
    <table class='table'>
      <tr>
        <td><%= 'Account Type:' %></td>
        <td><%= @profile.roles[0].name.capitalize %></td>
      </tr>
      <tr>
        <td><%= 'Username:' %></td>
        <td><%= @profile.username %></td>
      </tr>
      <tr>
        <td><%= 'Name:' %></td>
        <td><%= @profile.name %></td>
      </tr>
      <tr>
        <td><%= 'Contact Number:' %></td>
        <td><%= @profile.contact_number %></td>
      </tr>
      </table>
    <%= link_to("Edit Information", edit_profile_path(@profile), class: 'button is-warning') %>
  </section>

  <br />

  <section class='block'>
    <h4>Addresses</h4>
    <% @profile.addresses.each do |address| %>
      <div class="field has-background-info-light">
        <%= address.street_number %>
        <%= address.street_name %>
        <%= address.suburb %>
        <%= address.postcode %>
        <%= address.state %>
        <div class='field'>
          <%= link_to('Edit', edit_address_path(address), class: 'button is-warning is-small') %>
          <%= button_to('Remove', address_path(address), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'button is-danger is-small') %>
        </div>
      </div>
    <% end %>
    <%= link_to('New Address', new_address_path, class: "button is-primary") %><br />
  </section>
<% end %>

<% if (@profile.has_role? :merchant)%>
  <%= link_to('Inventory', inventory_path(@profile.inventory), class: 'button is-info') %><br />
<% end %>