config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Routes for Profiles
  get 'profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  patch 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id/merchant', to: 'profiles#merchant', as: 'profile_merchant'
  patch 'profiles/:id/customer', to: 'profiles#customer', as: 'profile_customer'

  # Routes for Addresses
  get 'addresses/new', to: 'addresses#new', as: 'new_address'
  post 'addresses', to: 'addresses#create'
  get 'addresses/:id/edit', to: 'addresses#edit', as: 'edit_address'
  patch '/addresses/:id', to: 'addresses#update', as: 'address'
  delete 'addresses/:id', to: 'addresses#destroy'
  

  # Routes for Inventories. These *only* need to be created.
  get 'inventories/:id', to: 'inventories#show', as: 'inventory'

  # Routes for Coffees
  get 'coffees', to: 'coffees#index'
  get 'coffees/new', to: 'coffees#new', as: 'new_coffee'
  post 'coffees', to: 'coffees#create'
  get 'coffees/:id/edit', to: 'coffees#edit', as: 'edit_coffee'
  post 'coffees/:id/edit', to: 'coffees#update'
  get 'coffees/:id/', to: 'coffees#show', as: 'coffee'
  delete 'coffees/:id', to: 'coffees#destroy'
  patch '/coffees/:id', to: 'coffees#update'

  # Routes for Carts
  get 'carts', to: 'carts#index', as: 'carts'
  get 'coffees/:id/carts/new', to: 'carts#create', as: 'new_cart'
  patch 'carts/:id/+1', to: 'carts#increase', as: 'cart_increase'
  patch 'carts/:id/-1', to: 'carts#decrease', as: 'cart_decrease'
  delete 'carts/checkout', to: 'carts#checkout', as: 'checkout'
  delete 'carts/:id', to: 'carts#remove', as: 'cart'

  root to: 'coffees#index'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :profile

  has_many :coffees, dependent: :destroy
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_auth
  before_action :set_profile, only: [:show]
  before_action :set_inventory

  def show
    @inventory = current_user.profile.inventory
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def check_auth
    authorize Inventory
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/show.html.erb
<h1><%= @inventory.profile[:username] %></h1>

<%= cl_image_tag(@inventory.profile.profile_picture.key, crop: :scale, width: 150, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if @inventory.profile.profile_picture.attached? %>

<section class='block'>
  <h4>Inventory</h4>
  <% @inventory.coffees.each do |coffee| %>
    <div class="field has-background-info-light">
    <%= cl_image_tag(coffee.coffee_image.key, crop: :scale, width: 150, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if coffee.coffee_image.attached? %><br />
    <%= 'Coffee:' %>
    <%= coffee.origin %>
    <%= coffee.name %><br />
    <%= 'Price:' %>
    <%= coffee.price %><br />
    <%= 'Description:' %>
    <%= coffee.description %><br />
    <%= 'Roast:' %>
    <%= coffee.roast_type %><br />
    <%= 'Quantity:' %>
    <%= coffee.quantity %><br />
    <div class='field'>
        <%= link_to('Edit', edit_coffee_path(coffee), class: 'button is-warning is-small') %>
        <%= button_to('Remove', coffee_path(coffee), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'button is-danger is-small') %>
    </div>
    </div>
  <% end %>
  <%= link_to('Add Coffee', new_coffee_path, class: "button is-primary") %><br />
</section>