config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Routes for Profiles
  get 'profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  patch 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id/merchant', to: 'profiles#merchant', as: 'profile_merchant'
  patch 'profiles/:id/customer', to: 'profiles#customer', as: 'profile_customer'

  # Routes for Addresses
  get 'addresses/new', to: 'addresses#new', as: 'new_address'
  post 'addresses', to: 'addresses#create'
  get 'addresses/:id/edit', to: 'addresses#edit', as: 'edit_address'
  patch '/addresses/:id', to: 'addresses#update', as: 'address'
  delete 'addresses/:id', to: 'addresses#destroy'
  

  # Routes for Inventories. These *only* need to be created.
  get 'inventories/:id', to: 'inventories#show', as: 'inventory'

  # Routes for Coffees
  get 'coffees', to: 'coffees#index'
  get 'coffees/new', to: 'coffees#new', as: 'new_coffee'
  post 'coffees', to: 'coffees#create'
  get 'coffees/:id/edit', to: 'coffees#edit', as: 'edit_coffee'
  post 'coffees/:id/edit', to: 'coffees#update'
  get 'coffees/:id/', to: 'coffees#show', as: 'coffee'
  delete 'coffees/:id', to: 'coffees#destroy'
  patch '/coffees/:id', to: 'coffees#update'

  # Routes for Carts
  get 'carts', to: 'carts#index', as: 'carts'
  get 'coffees/:id/carts/new', to: 'carts#create', as: 'new_cart'
  patch 'carts/:id/+1', to: 'carts#increase', as: 'cart_increase'
  patch 'carts/:id/-1', to: 'carts#decrease', as: 'cart_decrease'
  delete 'carts/checkout', to: 'carts#checkout', as: 'checkout'
  delete 'carts/:id', to: 'carts#remove', as: 'cart'

  root to: 'coffees#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :profile
  belongs_to :coffee

  validates :profile, presence: true
  validates :coffee, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/carts_controller.rb
# Carts are a joining table between Profiles and Coffees, and serve two main roles:
# 1 - Simulating a typical 'shopping cart' from an online store, by providing a collection of all Cart records
# associated with their profile
# 2 - Simulating purchases within the app
# A user viewing their cart is actually seeing a collection of individual Cart records associated with their profile
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_auth
  before_action :set_profile, only: %i[index new create checkout]
  before_action :set_coffee, only: [:create]
  before_action :set_cart, only: %i[increase decrease remove destroy]

  # Users should only see carts belonging to them
  def index
    @carts = Cart.where("profile_id = #{@profile.id}")
  end

  # Due to implementation (no forms, "Add to Cart" button), Cart creation requires special attention. This method
  # creates a new Cart, and assigns it's attibrutes afterwards to associate it with the correct profile and coffee
  # Creating also adjusts the available quantity of the appropriate Coffee. Calling 'increase' would be the preferred
  # solution, but it will not recognise a valid Cart object if called within this method. However this should not be
  # an issue, as the 'add to cart' button shouldn't be displayed unless there is at least 1 coffee available
  def create
    @cart = Cart.new
    @cart.profile = @profile
    @cart.coffee = @coffee
    @cart.quantity = 1
    @cart.coffee.quantity -= 1

    save?
  end

  # Checks that sufficient quantity of coffee exists before increasing cart quantity
  def stock?
    @cart.coffee.quantity.positive?
  end

  # Checks that Cart and Coffee have successfully saved their new values before finishing increase/decrease method
  def save?
    if @cart.save && @cart.coffee.save
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @cart.errors.full_messages.join('<br />').html_safe
      return
    end
  end

  # Check to prevents users from removing the last coffee from a Cart; to prevent a '0' quantity
  def not_last?
    @cart.quantity > 1
  end

  # Increase and Decrease are custom methods allowing users to add or remove items from their cart, and adjusting the
  # quantity of the involved coffee accordingly
  def increase
    if stock?
      @cart.quantity += 1
      @cart.coffee.quantity -= 1
    else
      flash[:alert] = "No more of this coffee is available"
    end

    save?
  end

  def decrease
    if not_last?
      @cart.quantity -= 1
      @cart.coffee.quantity += 1
    else
      flash[:alert] = "Can't decrease last item, please select Remove"
    end

    save?
  end

  # This is a custom method to delete a specific Cart record. To a user, this should appear to be removing a specific
  # item from their Cart. This method needs to "refund" the available quantity of the appropriate coffee, which
  # behaviour is NOT desired in the "Checkout" method that uses 'destroy'. To allow both of these methods to function
  # as intended, custom methods have been provided for both
  def remove
    @cart.coffee.quantity += @cart.quantity
    if @cart.coffee.save
      @cart.destroy
      redirect_to carts_path
      flash[:notice] = 'Item Removed'
    else
      flash[:alert] = @cart.errors.full_messages.join('<br />').html_safe
    end
  end

  # Payment has not been implemented. This method mimics purchasing all items by destroying all Carts associated with a
  # user's profile, without 'refunding' the coffee quantities back to their inventories
  def checkout
    @carts = Cart.where("profile_id = #{@profile.id}")
    @carts.each do |cart|
      cart.destroy
    end
    flash[:notice] = 'Purchase Successful'
    redirect_to carts_path
  end

  private

  def check_auth
    authorize Cart
  end

  def set_profile
    @profile = current_user.profile
  end

  def set_coffee
    @coffee = Coffee.find(params[:id])
  end

  def set_cart
    @cart = policy_scope(Cart).find(params[:id])
  end

  def cart_params
    return params.require(:cart).permit(:id, coffee_attributes: [:id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<h1>Your Cart</h1>

<%# Display cart total and 'Checkout' %>
<% total = 0 %>
<% @carts.each do |cart| %>
  
  <% total += cart.quantity * cart.coffee.price %>
  <% end %>
<h4>Total: <%= total.round(2) %></h4>
<%= button_to('Checkout', checkout_path, method: :delete, class: 'button is-danger is-small') %><br />

<%# Tile formatting from Bulma to allow multiple displays per row %>
<section class='tile is-ancestor is-flex-wrap-wrap is-justify-content-space-around'>

  <%# Displays a table for each cart, with individual edit/remove buttons %>
  <% @carts.each do |cart| %>

    <%# This requires multiple nested containers to display correctly %>
    <div class='tile is-5 m-3 is-flex'>
      <div class='is-child'>
        <%= cl_image_tag(cart.coffee.coffee_image.key, crop: :scale, width: 150, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) if cart.coffee.coffee_image.attached? %>

        <%# Creates 'table' effect for coffee information %>
        <table class='table'>
          <tr>
            <td><%= "#{cart.coffee.origin} #{cart.coffee.name}" %></td>
          </tr>
          
          <%# The Quantity section of the table requires different behaviour to house the adjustment buttons and current quantity display in visually acceptable style %>
          <tr>
            <td class='is-flex'>
              <div class='is-flex is-align-items-center'>
                <%= button_to("-1", cart_decrease_path(cart), method: :patch, class: 'button is-warning') %>
                <div class='has-background-info-light p-5'>
                  <%= cart.quantity %>
                </div>
                <%= button_to("+1", cart_increase_path(cart), method: :patch, class: 'button is-warning') %>
                </td>
              </div>
          </tr>

          <tr>
            <td><%= "Price: $ #{(cart.quantity * cart.coffee.price).round(2)}" %></td>
          </tr>

          <tr>
            <td><%= button_to('Remove', cart_path(cart), method: :delete, class: 'button is-danger is-small') %></td>  
          </tr>
        </table>
      </div>
    </div>
  <% end %>
</section>